// Generated by CoffeeScript 1.3.3
(function() {
  var Backbone, Game, Kit, Round, RoundList, root,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Backbone = require('backbone');

  Kit = require('../lib/Kit').Kit;

  Round = require('../lib/Round').Round;

  RoundList = (function(_super) {

    __extends(RoundList, _super);

    function RoundList() {
      return RoundList.__super__.constructor.apply(this, arguments);
    }

    RoundList.prototype.model = Round;

    return RoundList;

  })(Backbone.Collection);

  Game = (function(_super) {

    __extends(Game, _super);

    function Game() {
      return Game.__super__.constructor.apply(this, arguments);
    }

    Game.prototype.defaults = {
      values: [15, 16, 17, 18, 19, 20, 25]
    };

    return Game;

  })(Backbone.Model);

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Game = Game;

}).call(this);
